import streamlit as st
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util
import PyPDF2
import joblib
import re

# 1. Page Configuration
st.set_page_config(page_title="AI Resume Job Matcher", layout="wide")

# 2. Load Assets
@st.cache_resource
def load_assets():
    model = SentenceTransformer('all-MiniLM-L6-v2')
    scaler = joblib.load('semantic_scaler.pkl')
    return model, scaler

model, scaler = load_assets()

# --- HELPER FUNCTIONS ---
def extract_text(file):
    pdf = PyPDF2.PdfReader(file)
    return " ".join([page.extract_text() or "" for page in pdf.pages])

def get_keywords(text):
    """Simple cleaner to extract meaningful chunks for comparison"""
    # Removes special chars and splits by commas/bullets/newlines
    chunks = re.split(r'[,.\n•●/-]', text)
    return [c.strip() for c in chunks if len(c.strip()) > 3]

def analyze_skills(jd_text, resume_text):
    """Matches JD requirements to Resume text using SBERT"""
    jd_requirements = get_keywords(jd_text)[:20] # Focus on top 20 chunks
    resume_chunks = get_keywords(resume_text)
    
    matched = []
    gaps = []
    
    # Pre-encode resume for speed
    res_embs = model.encode(resume_chunks, convert_to_tensor=True)
    
    for req in jd_requirements:
        req_emb = model.encode(req, convert_to_tensor=True)
        # Check similarity against all chunks in the resume
        scores = util.cos_sim(req_emb, res_embs)[0]
        max_score = torch.max(scores).item()
        
        if max_score > 0.65: # Threshold for 'Semantic Match'
            matched.append(req)
        else:
            gaps.append(req)
            
    return list(set(matched)), list(set(gaps))


# 4 . Genarate downloaded output format
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import units
from reportlab.lib.pagesizes import A4
from io import BytesIO

def generate_pdf_report(df):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # Title
    elements.append(Paragraph("<b>Ranked Candidate Report</b>", styles['Heading1']))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Generated by AI Semantic Resume Matcher", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Table Data
    table_data = [["Rank", "Candidate Name", "Match Score (%)"]]

    for idx, row in df.reset_index(drop=True).iterrows():
        table_data.append([
            idx + 1,
            row["Candidate Name"],
            f"{row['Match Score']}%"
        ])

    table = Table(table_data, colWidths=[50, 250, 120])

    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ALIGN', (2,1), (2,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica')
    ]))

    elements.append(table)
    doc.build(elements)

    buffer.seek(0)
    return buffer

# --- UI LAYOUT ---
st.title("🎯 Semantic Resume-JD Matcher")
st.markdown("Rank resumes based on **meaning**, and see exactly what's missing.")

with st.sidebar:
    st.header("Step 1: Job Description")
    jd_input = st.text_area("Paste the Job Description here:", height=300)

st.header("Step 2: Upload Resumes")
uploaded_files = st.file_uploader("Upload candidate PDFs", type="pdf", accept_multiple_files=True)

if st.button("🚀 Analyze & Rank"):
    if not jd_input or not uploaded_files:
        st.error("Please provide both a JD and at least one resume.")
    else:
        results = []
        with st.spinner("Performing Deep Semantic Audit..."):
            for file in uploaded_files:
                text = extract_text(file)
                
                # 1. Calculate Calibrated Score
                jd_emb = model.encode(jd_input, convert_to_tensor=True)
                res_emb = model.encode(text, convert_to_tensor=True)
                raw_sim = util.cos_sim(jd_emb, res_emb).item()
                
                # Scaler expects 2D array
                calibrated = scaler.transform(np.array([[raw_sim]]))[0][0]
                final_score = round(calibrated * 100, 2)
                
                # 2. Analyze Matched vs Gaps
                matches, gaps = analyze_skills(jd_input, text)
                
                results.append({
                    "Candidate": file.name,
                    "Match Score": final_score,
                    "Matches": ", ".join(matches[:5]), # Show top 5 in table
                    "Gaps": ", ".join(gaps[:5]),
                    "Full_Matches": matches,
                    "Full_Gaps": gaps
                })
        
        df = pd.DataFrame(results).sort_values(by="Match Score", ascending=False)
        
        # Display main ranking table
        # st.subheader("📊 Ranked Candidates")
        # st.dataframe(df[["Candidate", "Match Score", "Matches", "Gaps"]], use_container_width=True)
        
        # # Detailed View for Top Candidate
        # st.divider()
        # top_c = df.iloc[0]
        # st.subheader(f"💡 Deep Dive: {top_c['Candidate']}")
        
        # col1, col2 = st.columns(2)
        # with col1:
        #     st.success("✅ Matched Skills")
        #     for m in top_c['Full_Matches']:
        #         st.write(f"- {m}")
        # with col2:
        #     st.warning("❌ Critical Gaps")
        #     for g in top_c['Full_Gaps']:
        #         st.write(f"- {g}")

        st.subheader("📊 Ranked Candidates")
        st.dataframe(df[["Candidate", "Match Score", "Matches", "Gaps"]], use_container_width=True)

        st.dataframe(
            df.style.highlight_max(axis=0, subset=['Match Score'], color='lightgreen'),
            use_container_width=True
        )

        st.success(f"Top candidate: {df.iloc[0]['Candidate Name']} with {df.iloc[0]['Match Score']}% match!")

        # --- Generate PDF ---
        pdf_buffer = generate_pdf_report(df)

        st.download_button(
            label="📄 Download Ranked Candidates Report (PDF)",
            data=pdf_buffer,
            file_name="Ranked_Candidates_Report.pdf",
            mime="application/pdf"
        )